= tyscheme

This archive contains the TeX source for the document _Teach
Yourself Scheme in Fixnum Days_.  It is written in plain-TeX
format and uses a BibTeX bibliography.  An HTML version may be
browsed online at

- http://ds26gte.github.io/tyscheme/index.html

To get a PDF version of the document, run

  luatex index
  bibtex index
  makeindex index
  mpost numint
  luatex index
  luatex index

The first tex run may cause an error because an
EPS file is missing.  Simply type `s` at the
TeX prompt to force TeX to continue.

The multiple runs of tex are needed to resolve
cross-references.  If the MetaPost executable
is named `mp` on your system (e.g., MiKTeX),
change `mpost` to `mp`.

To get an HTML version of the document, run

  tex2page index

a few times.  As with TeX, multiple runs of tex2page
are needed to resolve cross-references.  Each run
of tex2page will tell you if another run is necessary.

The tex2page program is available at

- https://github.com/ds26gte/tex2page

❧❧❧

Last modified: 2020-11-13
